sudo: required
dist: focal
language: ruby
rvm:
  - "2.4.0"
  - ruby-head
env:
  - "PGVERSION=14"
  - "PGVERSION=9.6"
before_install:
  - gem install bundler --no-doc --conservative
  - bundle install
  # Download and install postgresql version to test against in /opt (for non-cross compile only)
  - echo "deb http://apt.postgresql.org/pub/repos/apt/ ${TRAVIS_DIST}-pgdg main $PGVERSION" | sudo tee -a /etc/apt/sources.list.d/pgdg.list
  - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  - sudo apt -y update
  - sudo apt -y --allow-downgrades install postgresql-$PGVERSION libpq-dev
  - export PATH=/usr/lib/postgresql/$PGVERSION/bin:$PATH

script: rake test
